### ISSUE TITLE
TypeError: expected f64

### ISSUE THREAD

**Issue by 7flash** [asg017/sqlite-vss#112]
```
deno --version
deno 1.39.1 (release, aarch64-apple-darwin)
v8 12.0.267.8
typescript 5.3.3
```

Running example from README https://github.com/asg017/sqlite-vss?tab=readme-ov-file#deno

```
Warning Implicitly using latest version (v0.1.2) for https://deno.land/x/sqlite_vss/mod.ts
error: Uncaught (in promise) TypeError: expected f64
export const SQLITE_VERSION = readCstr(sqlite3_libversion());
                              ^
    at https://deno.land/x/sqlite3@0.8.0/src/database.ts:101:31
    at eventLoopTick (ext:core/01_core.js:181:11)
```

**Comment by 7flash** [comment]
This error throws in sqlite3@0.8.0 but works in sqlite3@0.10.0
